### ISSUE TITLE
Button Status Register 0x08 is always 1

### ISSUE THREAD

**Issue by fourstix** [sparkfun/Qwiic_Joystick#2]
Reading the button status through the Arduino library checkButton function or even directly through i2c calls to read register 0x08 always returns 1.  The register never seems to clear after being explicitly set to 0x00 through a write call in the library.  I traced the error through the Arduino library and it seems to be an issue with the firmware.

**Comment by fourstix** [comment]
I am using a Qwiic Joystick with a firmware version of v2.4.

**Comment by santaimpersonator** [comment]
You are correct, that is a firmware issue. I must have accidentally undone or overwrote that value in the protection map for the [Button_Status](https://github.com/sparkfun/Qwiic_Joystick/blob/master/Firmware/ATtiny85%20Firmware/Qwiic_Joystick_v24/Qwiic_Joystick_v24.ino#L93). There is one other thing I would like to double-check before updating the firmware again.

I'll have the tech support team reach out to you in the forum. Thanks for reaching out.

**Comment by santaimpersonator** [comment]
Firmware updated. Closing issue.
